project:
  type: website
  output-dir: docs
website:
  title: "Training of Trainees Master Class"
  site-url: https://github.com/sijuswamyresearch/Graph-Theory-Workshop-SBCE
  repo-url: https://github.com/sijuswamyresearch/Graph-Theory-Workshop-SBCE
  repo-branch: main
  repo-actions: [issue]
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About the ToT
      - href: feedback.qmd
        text: Feed Back  
  sidebar:
    style: "docked"
    logo: "./images/workshop_cover.png"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: Session1/index.qmd
        text: Four Pillers of AI
      - href: Session2/index.qmd
        text: The Language of AI
      - href: Session3/index.qmd
        text: The Engine of Learning
      - href: Session4/index.qmd
        text: The Science of Uncertainty
      - href: Session5/index.qmd
        text: The Strategy of Search 
      - href: Session6/index.qmd
        text: Pillars in Practice
      - href: session7/index.qmd
        text: Synthesis & Teaching Excellence

      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# Additional extensions for Sphinx
sphinx:
  config:
    html_js_files:
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid
body-header: | 
  This Cource is designed and implemented by Department of Mathematics
margin-header: |
  ![Sharing Innovations](/images//ASAP.jfif)